<?php
/**
 * Created by PhpStorm.
 * User: Claude Bing
 * Date: 12/18/2015
 * Time: 8:12 PM
 */

/**
 * This seemed to be the cleanest method to customize page titles.  Each array key is a path (app/<key part 1>/<key part 2>)
 */
$pageTitleArray = Array(
    'index' => 'Home',
    'about' => 'About',
    'about/disclaimer' => 'Disclaimer',
    'about/git' => 'Git Commit History',
    'about/privacy' => 'Privacy Policy',
    'about/statistics' => 'Site Statistics',
    'about/terms' => 'Terms of Use',
    'admin' => 'Administration Panel',
    'admin/activate-users' => 'Activate Users',
    'admin/afsc' => 'AFSC Manager',
    'admin/afsc-pending' => 'Approve AFSC Associations',
    'admin/authorize-users' => 'Authorize Users',
    'admin/base-overview' => 'Base Overview',
    'admin/bases' => 'Base Manager',
    'admin/card-data' => 'Flash Card Data',
    'admin/cdc-data' => 'CDC Data',
    'admin/flash-card-categories' => 'Flash Card Categories',
    'admin/list' => 'List Users',
    'admin/log' => 'System Log',
    'admin/log-detail' => 'Log Details',
    'admin/memcache' => 'Memcache Statistics',
    'admin/office-symbols' => 'Office Symbol Manager',
    'admin/profile' => 'User Profile',
    'admin/roles' => 'Role Manager',
    'admin/search' => 'Search Database',
    'admin/statistics' => 'System Statistics',
    'admin/tests' => 'Test Manager',
    'admin/upload' => 'Upload Files',
    'admin/users' => 'User Manager',
    'auth/activate' => 'Activate Account',
    'auth/login' => 'Log In',
    'auth/logout' => 'Log Out',
    'auth/register' => 'Register',
    'auth/reset' => 'Reset Password',
    'cards' => 'Flash Cards',
    'cards/categories' => 'Flash Card Categories',
    'cards/data' => 'Flash Card Data',
    'cards/study' => 'Study Flash Cards',
    'errors/403' => 'Access Forbidden',
    'errors/404' => 'Page Not Found',
    'errors/500' => 'Internal Server Error',
    'errors/maintenance' => 'Site Undergoing Maintenance',
    'report/question' => 'Report Question',
    'supervisor/generate-test' => 'Create Paper Tests',
    'supervisor/history' => 'User Test History',
    'supervisor/history-split' => 'User Split Test History',
    'supervisor/log' => 'User Log',
    'supervisor/log-detail' => 'User Log Detail',
    'supervisor/overview' => 'Supervisor Overview',
    'supervisor/profile' => 'User Profile',
    'supervisor/subordinates' => 'Subordinate Manager',
    'supervisor/top-missed' => 'Top Missed Questions',
    'test/delete' => 'Delete Test',
    'test/resume' => 'Resume Test',
    'test/score' => 'Score Test',
    'test/take' => 'Take Test',
    'test/view' => 'View Test',
    'training/generate-test' => 'Create Paper Tests',
    'training/overview' => 'Training Manager Overview',
    'training/top-missed' => 'Top Missed Questions',
    'user/afsc-associations' => 'Manage AFSC Associations',
    'user/disable' => 'Disable Account',
    'user/edit' => 'Edit Profile',
    'user/history' => 'Test History',
    'user/history-split' => 'Split Test History',
    'user/log' => 'User Log',
    'user/log-detail' => 'User Log Detail',
    'user/profile' => 'My Profile',
    'user/top-missed' => 'Top 20 Missed Questions'
);